# ==========================
# Spring Application
# ==========================

spring.application.name=oauth-service
server.port=8080

# ==========================
# H2 Database Configuration (User store)
# ==========================

spring.datasource.url=jdbc:h2:mem:authdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ==========================
# JPA Configuration
# ==========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ==========================
# H2 Console
# ==========================

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ==========================
# Logging
# ==========================

logging.level.root=INFO
logging.level.org.example=INFO
logging.file.name=logs/oauth-service.log

# ==========================
# Swagger
# ==========================

springdoc.swagger-ui.operationsSorter=method

# ==========================
# Google OAuth2
# ==========================

spring.security.oauth2.client.registration.google.client-id=51331647757-vhrovg0ojd8qm4mriu10ucr74aevc8h4.apps.googleusercontent.com

spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,email,profile

# ==========================
# JWT
# ==========================

app.jwt.secret=your-256-bit-secret-key-change-in-production
app.jwt.expiration=86400000

# ==========================
# Frontend
# ==========================

app.frontend.url=http://localhost:5173
